---
# roles/apps/listmonk/tasks/deploy.yml

- name: Create Listmonk directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ listmonk_stack_path }}"
    - "{{ listmonk_data_path }}"

- name: Deploy Listmonk docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ listmonk_stack_path }}/docker-compose.yml"
    mode: "0644"

- name: Deploy Listmonk .env
  ansible.builtin.template:
    src: env.j2
    dest: "{{ listmonk_stack_path }}/.env"
    mode: "0600"

- name: Start Listmonk
  community.docker.docker_compose_v2:
    project_src: "{{ listmonk_stack_path }}"
    state: present

- name: Wait for Listmonk to be ready
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ listmonk_port }}{{ listmonk_health_path }}"
    method: GET
    status_code: [200, 301, 302]
  register: listmonk_health
  until: listmonk_health.status in [200, 301, 302]
  retries: 30
  delay: 5
