---
# roles/apps/paperless/handlers/main.yml

- name: restart caddy
  ansible.builtin.command: docker restart caddy
  changed_when: true

- name: restart paperless
  ansible.builtin.command: docker restart paperless
  changed_when: true
