---
# roles/apps/hedgedoc/handlers/main.yml

- name: restart caddy
  ansible.builtin.command: docker restart caddy
  changed_when: true

- name: restart hedgedoc
  ansible.builtin.command: docker restart hedgedoc
  changed_when: true
