---
# roles/apps/outline/handlers/main.yml

- name: restart caddy
  ansible.builtin.command: docker restart caddy
  changed_when: true

- name: restart outline
  ansible.builtin.command: docker restart outline
  changed_when: true
