---
# roles/baserow/handlers/main.yml

- name: restart caddy
  ansible.builtin.command: docker restart caddy
  changed_when: true

- name: restart baserow
  ansible.builtin.command: docker restart baserow
  changed_when: true
