---
# roles/gocryptfs/handlers/main.yml

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart gocryptfs-mount
  ansible.builtin.systemd:
    name: gocryptfs-mount
    state: restarted
